<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NAVEEN" failures="2" tests="3" name="IE Test" time="34.924" errors="0" timestamp="2022-08-29T16:44:08 IST">
  <testcase classname="lambdatestjava.LambdaTestJava2" name="testScenario2" time="5.764">
    <failure type="java.lang.AssertionError" message="expected [95] but found [51]">
      <![CDATA[java.lang.AssertionError: expected [95] but found [51]
at lambdatestjava.LambdaTestJava2.testScenario2(LambdaTestJava2.java:76)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testScenario2 -->
  <testcase classname="lambdatestjava.LambdaTestJava3" name="testScenario3" time="5.615">
    <failure type="java.lang.AssertionError" message="expected [Please fill out this field.] but found [This is a required field]">
      <![CDATA[java.lang.AssertionError: expected [Please fill out this field.] but found [This is a required field]
at lambdatestjava.LambdaTestJava3.testScenario3(LambdaTestJava3.java:60)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testScenario3 -->
  <testcase classname="lambdatestjava.LambdaTestJava" name="testScenario1" time="6.731"/>
</testsuite> <!-- IE Test -->
